import type { Vehicle } from '@/types'

/**
 * Mock vehicle data for development without Supabase.
 * Mirrors the seed.sql entries.
 */
export const mockVehicles: Vehicle[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    slug: 'audi-a3-sportback-35-tdi-s-tronic-2021',
    brand: 'Audi',
    model: 'A3 Sportback',
    version: '35 TDI S-Tronic',
    year: 2021,
    mileage: 45000,
    fuel_type: 'diesel',
    transmission: 'automatico',
    power_hp: 150,
    power_kw: 110,
    engine_cc: 1968,
    body_type: 'Berlina',
    color_exterior: 'Grigio Nardo',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: false,
    price: 28900,
    monthly_payment: 602.08,
    description:
      'Audi A3 Sportback in eccellenti condizioni. Unico proprietario, tagliandi certificati Audi. Dotazione completa con navigatore MMI Plus, sedili sportivi e cerchi in lega 18".',
    features: {
      comfort: [
        'Climatizzatore automatico bi-zona',
        'Sedili sportivi riscaldati',
        'Sensori parcheggio ant/post',
        'Retrocamera',
        'Cruise control adattivo',
      ],
      sicurezza: [
        '6 airbag',
        'ABS',
        'ESP',
        'Lane assist',
        'Frenata automatica',
      ],
      infotainment: [
        'MMI Navigation Plus',
        'Apple CarPlay',
        'Android Auto',
        'Virtual Cockpit',
        'Bang & Olufsen',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    images: [
      {
        id: 'img-0001-01',
        vehicle_id: 'a1b2c3d4-0001-4000-8000-000000000001',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'img-0001-02',
        vehicle_id: 'a1b2c3d4-0001-4000-8000-000000000001',
        url: '/images/placeholder-car.jpg',
        position: 1,
        is_cover: false,
        created_at: '2024-01-15T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    slug: 'bmw-serie-3-320d-msport-2022',
    brand: 'BMW',
    model: 'Serie 3',
    version: '320d MSport',
    year: 2022,
    mileage: 32000,
    fuel_type: 'diesel',
    transmission: 'automatico',
    power_hp: 190,
    power_kw: 140,
    engine_cc: 1995,
    body_type: 'Berlina',
    color_exterior: 'Nero Sapphire',
    color_interior: 'Pelle Vernasca Nero',
    doors: 4,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'RWD',
    new_driver_ok: false,
    price: 38500,
    monthly_payment: 802.08,
    description:
      'BMW 320d MSport con pacchetto sportivo completo. Auto in condizioni pari al nuovo con tutti i tagliandi BMW. Cerchi M da 19", interni in pelle Vernasca.',
    features: {
      comfort: [
        'Climatizzatore automatico tri-zona',
        'Sedili sportivi M riscaldati',
        'Parcheggio assistito',
        'Head-up display',
        'Volante sportivo M',
      ],
      sicurezza: [
        'Driving Assistant Professional',
        '8 airbag',
        'Telecamera 360°',
        'Park Distance Control',
      ],
      infotainment: [
        'BMW Live Cockpit Professional',
        'Apple CarPlay wireless',
        'Harman Kardon',
        'WiFi hotspot',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-16T10:00:00Z',
    images: [
      {
        id: 'img-0002-01',
        vehicle_id: 'a1b2c3d4-0002-4000-8000-000000000002',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-16T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    slug: 'fiat-500-dolcevita-2023',
    brand: 'Fiat',
    model: '500',
    version: '1.0 Hybrid Dolcevita',
    year: 2023,
    mileage: 12000,
    fuel_type: 'ibrida',
    transmission: 'manuale',
    power_hp: 70,
    power_kw: 51,
    engine_cc: 999,
    body_type: 'Berlina',
    color_exterior: 'Bianco Gelato',
    color_interior: 'Beige/Avorio',
    doors: 3,
    seats: 4,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: true,
    price: 16900,
    monthly_payment: 352.08,
    description:
      "Fiat 500 Hybrid nell'allestimento Dolcevita con tetto apribile in tela. Perfetta per la città, consumi ridottissimi. Praticamente nuova con soli 12.000 km.",
    features: {
      comfort: [
        'Climatizzatore automatico',
        'Tetto apribile in tela',
        'Sensori parcheggio posteriori',
        'Specchietti cromati',
        'Volante in pelle',
      ],
      sicurezza: ['6 airbag', 'ABS', 'ESP', 'Hill holder'],
      infotainment: [
        'Uconnect 7" touchscreen',
        'Apple CarPlay',
        'Android Auto',
        'DAB+',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-17T10:00:00Z',
    images: [
      {
        id: 'img-0003-01',
        vehicle_id: 'a1b2c3d4-0003-4000-8000-000000000003',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-17T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    slug: 'volkswagen-golf-8-life-2022',
    brand: 'Volkswagen',
    model: 'Golf',
    version: '8 2.0 TDI Life',
    year: 2022,
    mileage: 55000,
    fuel_type: 'diesel',
    transmission: 'manuale',
    power_hp: 115,
    power_kw: 85,
    engine_cc: 1968,
    body_type: 'Berlina',
    color_exterior: 'Blu Atlantico',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: false,
    price: 22500,
    monthly_payment: 468.75,
    description:
      'Volkswagen Golf 8 Life con motore 2.0 TDI da 115 CV. Ottima per chi cerca affidabilità e bassi consumi. Tagliandi regolari, gomme nuove.',
    features: {
      comfort: [
        'Climatizzatore automatico',
        'Cruise control',
        'Sensori parcheggio post',
        'Sedile guida regolabile elettricamente',
      ],
      sicurezza: ['Front Assist', 'Lane Assist', '6 airbag', 'ESP'],
      infotainment: [
        'Discover Media 10"',
        'Apple CarPlay',
        'Android Auto',
        'Digital Cockpit',
      ],
    },
    is_featured: false,
    status: 'disponibile',
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-18T10:00:00Z',
    images: [
      {
        id: 'img-0004-01',
        vehicle_id: 'a1b2c3d4-0004-4000-8000-000000000004',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-18T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0005-4000-8000-000000000005',
    slug: 'toyota-yaris-cross-adventure-2023',
    brand: 'Toyota',
    model: 'Yaris Cross',
    version: '1.5 Hybrid Adventure',
    year: 2023,
    mileage: 18000,
    fuel_type: 'ibrida',
    transmission: 'automatico',
    power_hp: 116,
    power_kw: 85,
    engine_cc: 1490,
    body_type: 'SUV',
    color_exterior: 'Verde Cypress',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'AWD',
    new_driver_ok: false,
    price: 27500,
    monthly_payment: 572.92,
    description:
      'Toyota Yaris Cross Adventure con trazione integrale AWD-i. Ibrida full hybrid senza necessità di ricarica. Garanzia Toyota ancora attiva.',
    features: {
      comfort: [
        'Climatizzatore automatico',
        'Sedile guida riscaldato',
        'Portellone elettrico',
        'Retrocamera',
        'Cruise control adattivo',
      ],
      sicurezza: [
        'Toyota Safety Sense 3.0',
        '7 airbag',
        'Blind spot monitor',
        'Rear cross traffic alert',
      ],
      infotainment: [
        'Display 9" touchscreen',
        'Apple CarPlay wireless',
        'Android Auto wireless',
        'JBL Premium Audio',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-19T10:00:00Z',
    updated_at: '2024-01-19T10:00:00Z',
    images: [
      {
        id: 'img-0005-01',
        vehicle_id: 'a1b2c3d4-0005-4000-8000-000000000005',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-19T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    slug: 'mercedes-classe-a-200d-amg-2021',
    brand: 'Mercedes-Benz',
    model: 'Classe A',
    version: '200d AMG Line',
    year: 2021,
    mileage: 48000,
    fuel_type: 'diesel',
    transmission: 'automatico',
    power_hp: 150,
    power_kw: 110,
    engine_cc: 1950,
    body_type: 'Berlina',
    color_exterior: 'Grigio Montagna',
    color_interior: 'Nero/Rosso',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: false,
    price: 31900,
    monthly_payment: 664.58,
    description:
      'Mercedes Classe A 200d con pacchetto AMG Line. Interni bicolore nero/rosso esclusivi. MBUX con doppio schermo da 10.25". Perfetta combinazione di sportività ed eleganza.',
    features: {
      comfort: [
        'THERMOTRONIC bi-zona',
        'Sedili sportivi AMG',
        'Ambient light 64 colori',
        'Keyless-Go',
        'Specchietti MEMORY',
      ],
      sicurezza: [
        'Active Brake Assist',
        'Attention Assist',
        '7 airbag',
        'Active Lane Keep Assist',
      ],
      infotainment: [
        'MBUX 10.25" doppio display',
        'Apple CarPlay',
        'Android Auto',
        'Navigatore',
        'Burmester sound',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    images: [
      {
        id: 'img-0006-01',
        vehicle_id: 'a1b2c3d4-0006-4000-8000-000000000006',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-20T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    slug: 'jeep-renegade-limited-2020',
    brand: 'Jeep',
    model: 'Renegade',
    version: '1.6 Multijet Limited',
    year: 2020,
    mileage: 62000,
    fuel_type: 'diesel',
    transmission: 'manuale',
    power_hp: 130,
    power_kw: 96,
    engine_cc: 1598,
    body_type: 'SUV',
    color_exterior: 'Bianco Alpine',
    color_interior: 'Pelle Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: false,
    price: 19900,
    monthly_payment: 414.58,
    description:
      'Jeep Renegade Limited con interni in pelle e navigatore Uconnect 8.4". Ottimo stato, gomme 4 stagioni recenti. Ideale per chi cerca un SUV compatto ben accessoriato.',
    features: {
      comfort: [
        'Climatizzatore automatico bi-zona',
        'Sedili in pelle riscaldati',
        'Sensori parcheggio ant/post',
        'Cruise control',
        'My Sky panoramico',
      ],
      sicurezza: [
        'Lane Departure Warning',
        'Forward Collision Warning',
        '6 airbag',
        'Hill descent control',
      ],
      infotainment: [
        'Uconnect 8.4" NAV',
        'Apple CarPlay',
        'Android Auto',
        'Beats Audio',
      ],
    },
    is_featured: false,
    status: 'disponibile',
    created_at: '2024-01-21T10:00:00Z',
    updated_at: '2024-01-21T10:00:00Z',
    images: [
      {
        id: 'img-0007-01',
        vehicle_id: 'a1b2c3d4-0007-4000-8000-000000000007',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-21T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0008-4000-8000-000000000008',
    slug: 'ford-puma-st-line-2023',
    brand: 'Ford',
    model: 'Puma',
    version: '1.0 EcoBoost 125 Hybrid ST-Line',
    year: 2023,
    mileage: 15000,
    fuel_type: 'ibrida',
    transmission: 'manuale',
    power_hp: 125,
    power_kw: 92,
    engine_cc: 999,
    body_type: 'SUV',
    color_exterior: 'Rosso Lucid',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: true,
    price: 24500,
    monthly_payment: 510.42,
    description:
      'Ford Puma ST-Line con motore EcoBoost Hybrid da 125 CV. Design sportivo, MegaBox nel bagagliaio. Pochissimi km, condizioni eccellenti.',
    features: {
      comfort: [
        'Climatizzatore automatico',
        'Sedili sportivi ST-Line',
        'Portellone hands-free',
        'MegaBox bagagliaio',
        'Cruise control adattivo',
      ],
      sicurezza: [
        'Co-Pilot360',
        'Pre-Collision Assist',
        '6 airbag',
        'Blind Spot Information System',
      ],
      infotainment: [
        'SYNC 3 8" touchscreen',
        'Apple CarPlay',
        'Android Auto',
        'FordPass Connect',
        'B&O sound',
      ],
    },
    is_featured: true,
    status: 'disponibile',
    created_at: '2024-01-22T10:00:00Z',
    updated_at: '2024-01-22T10:00:00Z',
    images: [
      {
        id: 'img-0008-01',
        vehicle_id: 'a1b2c3d4-0008-4000-8000-000000000008',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-22T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0009-4000-8000-000000000009',
    slug: 'renault-clio-intens-2022',
    brand: 'Renault',
    model: 'Clio',
    version: '1.0 TCe 100 Intens',
    year: 2022,
    mileage: 35000,
    fuel_type: 'benzina',
    transmission: 'manuale',
    power_hp: 100,
    power_kw: 74,
    engine_cc: 999,
    body_type: 'Berlina',
    color_exterior: 'Arancio Valencia',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: true,
    price: 15500,
    monthly_payment: 322.92,
    description:
      'Renault Clio Intens con motore turbo benzina da 100 CV. Colore esclusivo Arancio Valencia. Ottima dotazione di serie con navigatore e sensori.',
    features: {
      comfort: [
        'Climatizzatore automatico',
        'Sensori parcheggio post con retrocamera',
        'Cruise control',
        'Bracciolo centrale',
      ],
      sicurezza: [
        'Highway & Traffic Jam Companion',
        'Lane Centering',
        '6 airbag',
        'Active Emergency Braking',
      ],
      infotainment: [
        'Easy Link 9.3" touchscreen',
        'Apple CarPlay',
        'Android Auto',
        'Navigatore integrato',
      ],
    },
    is_featured: false,
    status: 'disponibile',
    created_at: '2024-01-23T10:00:00Z',
    updated_at: '2024-01-23T10:00:00Z',
    images: [
      {
        id: 'img-0009-01',
        vehicle_id: 'a1b2c3d4-0009-4000-8000-000000000009',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-23T10:00:00Z',
      },
    ],
  },
  {
    id: 'a1b2c3d4-0010-4000-8000-000000000010',
    slug: 'hyundai-tucson-xline-2022',
    brand: 'Hyundai',
    model: 'Tucson',
    version: '1.6 CRDi 136 48V XLine',
    year: 2022,
    mileage: 42000,
    fuel_type: 'diesel',
    transmission: 'automatico',
    power_hp: 136,
    power_kw: 100,
    engine_cc: 1598,
    body_type: 'SUV',
    color_exterior: 'Grigio Shadow',
    color_interior: 'Nero',
    doors: 5,
    seats: 5,
    emission_class: 'Euro 6d',
    drive_type: 'FWD',
    new_driver_ok: false,
    price: 29900,
    monthly_payment: 622.92,
    description:
      'Hyundai Tucson XLine con motore diesel mild-hybrid e cambio automatico DCT. Design avveniristico, interni spaziosi e tecnologici. Garanzia Hyundai 5 anni/km illimitati ancora attiva.',
    features: {
      comfort: [
        'Climatizzatore automatico bi-zona',
        'Sedile guida elettrico con memory',
        'Portellone elettrico smart',
        'Heated steering wheel',
        'Ventilated front seats',
      ],
      sicurezza: [
        'SmartSense completo',
        'Blind-Spot Collision-Avoidance',
        '7 airbag',
        'Highway Driving Assist',
      ],
      infotainment: [
        'Display 10.25" touchscreen',
        'Digital Cluster 10.25"',
        'Apple CarPlay wireless',
        'Android Auto wireless',
        'Krell Premium Audio',
      ],
    },
    is_featured: false,
    status: 'riservata',
    created_at: '2024-01-24T10:00:00Z',
    updated_at: '2024-01-24T10:00:00Z',
    images: [
      {
        id: 'img-0010-01',
        vehicle_id: 'a1b2c3d4-0010-4000-8000-000000000010',
        url: '/images/placeholder-car.jpg',
        position: 0,
        is_cover: true,
        created_at: '2024-01-24T10:00:00Z',
      },
    ],
  },
]
